version: '3'
services:
  db:
    image: mongo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
        - "27017:27017"
    volumes:
      - ./db:/var/lib/mysql

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      DB_HOST: db
    depends_on:
      - db
      