name: CI

on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install vitest
        working-directory: backend
        run: npm install 

      - name: Coverage Test
        working-directory: backend
        run: npm run test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: backend/coverage/index.html

      - name: compare
        uses: actions/download-artifact@v1
        with:
          name: code-coverage-report
          path: backend/index.html
        run: diff backend/coverage/index.html backend/index.html
          
  
