name: CI

on: [push]
jobs:
  coverate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Backend
        run: cd backend
        
      - name: Install vitest
        run: npm install 

      - name: Coverage Test
        run: npm run test
  
